name: tangem_sdk
description: TangemSdk flutter plugin.
version: 0.8.0
homepage: https://github.com/Tangem/tangem-sdk-flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  convert: ^3.0.0
  json_annotation: ^4.0.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  json_serializable: ^6.6.1


flutter:
  plugin:
    platforms:
      android:
        package: com.tangem.tangem_sdk
        pluginClass: TangemSdkPlugin
      ios:
        pluginClass: TangemSdkPlugin